## __2 - Detectando e Corrigindo Dados__

In [1]:
# Icluindo diretório dos módulos no paht
import sys

path_modulos = sys.path[0].rstrip("notebooks") + "modulos"
sys.path.append(path_modulos)

# Bibliotecas para análise de dados
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import rcParams
import seaborn as sns

# Bibliotecas para modelagem e acesso aos dados
from subestacoes import Subestacao, Info ,string_conexao, PontoDeMedicao

plt.style.use('seaborn')
rcParams['figure.figsize'] = [12, 8]

In [3]:
# String de Conexão
con = string_conexao()

info = Info(con)
tabela_info = info.get_tabela_info()
tabela_info

{'ABR': {'nome': 'Alto Branco',
  'latitude': -7.204444,
  'longitude': -35.872778},
 'AER': {'nome': 'Aeroclube', 'latitude': -7.263583, 'longitude': -35.892361},
 'ARA': {'nome': 'Areia', 'latitude': -6.972972, 'longitude': -35.705833},
 'ARN': {'nome': 'Araruna', 'latitude': -6.534722, 'longitude': -35.733194},
 'ARR': {'nome': 'Aroeiras', 'latitude': -7.55675, 'longitude': -35.727166},
 'BJC': {'nome': 'Brejo do Cruz',
  'latitude': -6.344611,
  'longitude': -37.499972},
 'BNR': {'nome': 'Bananeiras', 'latitude': -6.76, 'longitude': -35.644444},
 'BQR': {'nome': 'Boqueirão', 'latitude': -7.485486, 'longitude': -36.136219},
 'BSA': {'nome': 'Bessa', 'latitude': -7.087083, 'longitude': -34.850416},
 'BVA': {'nome': 'Boa Vista', 'latitude': -7.288916, 'longitude': -36.241805},
 'CAA': {'nome': 'Caaporã', 'latitude': -7.514547, 'longitude': -34.888266},
 'CBD': {'nome': 'Cabedelo', 'latitude': -7.027361, 'longitude': -34.840166},
 'CDE': {'nome': 'Conde', 'latitude': -7.262527, 'longitude': -34.937111},
 'CJZ': {'nome': 'Cajazeiras', 'latitude': -6.891389, 'longitude': -38.551667},
 'CPX': {'nome': 'Cruz do Peixe',
  'latitude': -7.118138,
  'longitude': -34.867361},
 'CRI': {'nome': 'Cristo', 'latitude': -7.16714, 'longitude': -34.877053},
 'CRM': {'nome': 'Coremas', 'latitude': -7.021888, 'longitude': -37.942138},
 'CTE': {'nome': 'Cuité', 'latitude': -6.47875, 'longitude': -36.157916},
 'CTL': {'nome': 'Catolé', 'latitude': -7.248277, 'longitude': -35.883972},
 'CTR': {'nome': 'Catolé do Rocha',
  'latitude': -6.348222,
  'longitude': -37.749888},
 'DIN': {'nome': 'Dona Inês', 'latitude': -6.614083, 'longitude': -35.626444},
 'DST': {'nome': 'Distrito', 'latitude': -7.178888, 'longitude': -34.907499},
 'ESP': {'nome': 'Esperança', 'latitude': -7.027055, 'longitude': -35.865527},
 'GBA': {'nome': 'Guarabira', 'latitude': -6.876722, 'longitude': -35.478222},
 'IBR': {'nome': 'Ibiara', 'latitude': -7.495, 'longitude': -38.405},
 'ILB': {'nome': 'Ilha do Bispo', 'latitude': -7.131, 'longitude': -34.903861},
 'ITA': {'nome': 'Itabaiana', 'latitude': -7.338277, 'longitude': -35.338055},
 'ITO': {'nome': 'Itaporanga', 'latitude': -7.300277, 'longitude': -38.126555},
 'JCU': {'nome': 'Jacaraú', 'latitude': -6.564166, 'longitude': -37.79611},
 'JPS': {'nome': 'João Pessoa', 'latitude': -7.129694, 'longitude': -34.86775},
 'JRC': {'nome': 'Jerico', 'latitude': -6.564277, 'longitude': -37.796055},
 'JTB': {'nome': 'Jatobá', 'latitude': -7.051138, 'longitude': -37.279388},
 'JZR': {'nome': 'Juazeirinho',
  'latitude': -7.067472,
  'longitude': -36.569555},
 'LCN': {'nome': 'Lucena', 'latitude': -6.94475, 'longitude': -34.907444},
 'MAA': {'nome': 'Mataraca', 'latitude': -6.5933, 'longitude': -35.058694},
 'MGB': {'nome': 'Mangabeira', 'latitude': -7.161722, 'longitude': -34.820222},
 'MLT': {'nome': 'Malta', 'latitude': -6.904138, 'longitude': -37.525694},
 'MNT': {'nome': 'Monteiro', 'latitude': -7.901944, 'longitude': -37.122055},
 'MRO': {'nome': 'Mata Redonda',
  'latitude': -7.335047,
  'longitude': -34.950605},
 'MRU': {'nome': 'Mussuré I', 'latitude': -7.179722, 'longitude': -34.893444},
 'ORT': {'nome': 'Oratório', 'latitude': -7.38575, 'longitude': -35.148611},
 'PBL': {'nome': 'Pombal', 'latitude': -6.778222, 'longitude': -37.809222},
 'PCI': {'nome': 'Picuí', 'latitude': -6.5115, 'longitude': -36.356611},
 'PCO': {'nome': 'Piancó', 'latitude': -7.214361, 'longitude': -37.967333},
 'PLT': {'nome': 'Paulista', 'latitude': -6.602877, 'longitude': -37.611833},
 'PLU': {'nome': 'Pilões I', 'latitude': -6.869666, 'longitude': -35.606999},
 'PLV': {'nome': 'Pedra Lavrada', 'latitude': -6.52812, 'longitude': -38.4159},
 'PRI': {'nome': 'Princesa Isabel',
  'latitude': -7.214361,
  'longitude': -37.967333},
 'PRT': {'nome': 'Paratibe', 'latitude': -7.210897, 'longitude': -34.829038},
 'PTS': {'nome': 'Patos', 'latitude': -7.005833, 'longitude': -37.298222},
 'QMD': {'nome': 'Queimadas', 'latitude': -7.371805, 'longitude': -35.916611},
 'RIC': {'nome': 'Riachão', 'latitude': -7.246777, 'longitude': -35.662361},
 'RTT': {'nome': 'Rio Tinto', 'latitude': -6.815768, 'longitude': -35.101072},
 'SBT': {'nome': 'São Bento', 'latitude': -6.509311, 'longitude': -37.446061},
 'SGL': {'nome': 'São Gonçalo', 'latitude': -6.52812, 'longitude': -38.4159},
 'SJC': {'nome': 'São João de Cariri',
  'latitude': -7.38375,
  'longitude': -36.525944},
 'SLZ': {'nome': 'Santa Luzia',
  'latitude': -6.877583,
  'longitude': -36.931305},
 'SME': {'nome': 'Sumé', 'latitude': -7.669916, 'longitude': -36.872555},
 'SPE': {'nome': 'Sapé', 'latitude': -7.087472, 'longitude': -35.221916},
 'SPX': {'nome': 'S.J. Rio do Peixe',
  'latitude': -6.725861,
  'longitude': -38.454555},
 'STR': {'nome': 'Santa Rita', 'latitude': -7.16714, 'longitude': -34.877053},
 'SZA': {'nome': 'Souza', 'latitude': -6.779444, 'longitude': -38.255},
 'TBU': {'nome': 'Tambaú', 'latitude': -7.115555, 'longitude': -34.834027},
 'TXR': {'nome': 'Teixeira', 'latitude': -7.222777, 'longitude': -37.243611},
 'URN': {'nome': 'Uiraúna', 'latitude': -6.528138, 'longitude': -38.415916}}

In [4]:
jps = Subestacao('JPS', tabela_info['JPS'].get("nome"), con)

In [5]:
jps_df = jps.get_tabela(con)  
jps_df.head()

,data,JPS_TIPO_12B1_WATT,JPS_TIPO_12B2_WATT,JPS_TIPO_11B1_WATT,JPS_TIPO_11B2_WATT,JPS_TIPO_21L1_WATT,JPS_TIPO_21L2_WATT,JPS_TIPO_21L3_WATT,JPS_TIPO_21L4_WATT,JPS_TIPO_21L5_WATT,JPS_TIPO_21L6_WATT,JPS_TIPO_21L7_WATT,JPS_TIPO_21L8_WATT,JPS_TIPO_21L9_WATT
0,2008-01-01 00:00:00,7.9,10.2,7.8,10.2,1.961,0.561,0.988,1.220,0.877,3.361,2.294,1.737,3.618
1,2008-01-01 00:15:00,7.7,10.1,7.7,10.0,1.938,0.556,0.968,1.167,0.840,3.339,2.227,1.798,3.469
2,2008-01-01 00:30:00,7.7,9.8,7.7,10.0,1.933,0.567,0.894,1.174,0.843,3.291,2.115,1.653,3.546
3,2008-01-01 00:45:00,7.4,9.8,7.4,10.0,1.892,0.567,0.894,1.176,0.815,3.211,2.066,1.630,3.376
4,2008-01-01 01:00:00,0.0,0.0,0.0,0.0,1.860,0.000,0.864,1.146,0.812,3.268,2.027,1.667,3.483

In [8]:
jps_df.set_index("data", inplace = True)
jps_df.head()

,JPS_TIPO_12B1_WATT,JPS_TIPO_12B2_WATT,JPS_TIPO_11B1_WATT,JPS_TIPO_11B2_WATT,JPS_TIPO_21L1_WATT,JPS_TIPO_21L2_WATT,JPS_TIPO_21L3_WATT,JPS_TIPO_21L4_WATT,JPS_TIPO_21L5_WATT,JPS_TIPO_21L6_WATT,JPS_TIPO_21L7_WATT,JPS_TIPO_21L8_WATT,JPS_TIPO_21L9_WATT
data,,,,,,,,,,,,,
2008-01-01 00:00:00,7.9,10.2,7.8,10.2,1.961,0.561,0.988,1.220,0.877,3.361,2.294,1.737,3.618
2008-01-01 00:15:00,7.7,10.1,7.7,10.0,1.938,0.556,0.968,1.167,0.840,3.339,2.227,1.798,3.469
2008-01-01 00:30:00,7.7,9.8,7.7,10.0,1.933,0.567,0.894,1.174,0.843,3.291,2.115,1.653,3.546
2008-01-01 00:45:00,7.4,9.8,7.4,10.0,1.892,0.567,0.894,1.176,0.815,3.211,2.066,1.630,3.376
2008-01-01 01:00:00,0.0,0.0,0.0,0.0,1.860,0.000,0.864,1.146,0.812,3.268,2.027,1.667,3.483

In [9]:
# Substituindo zeros por valores nulos

jps_nulos = jps_df.replace(0, np.nan)

### __Identificando outiliers utilizando perfil diário__

In [12]:
# Escolhendo colunas de medição

col1 = 'JPS_TIPO_11B1_WATT'
col2 = 'JPS_TIPO_21L6_WATT'

                     JPS_TIPO_11B1_WATT  JPS_TIPO_21L6_WATT
data
2011-01-03 00:00:00                11.7               2.226
2011-01-03 00:15:00                11.4               2.210
2011-01-03 00:30:00                11.3               2.172
2011-01-03 00:45:00                11.0               2.063
2011-01-03 01:00:00                11.0               2.046
...                                 ...                 ...
2011-12-26 22:45:00                 7.2               2.382
2011-12-26 23:00:00                 6.9               2.363
2011-12-26 23:15:00                 6.9               2.407
2011-12-26 23:30:00                 6.7               2.380
2011-12-26 23:45:00                 6.7               2.337

[4992 rows x 2 columns]

In [13]:
jps_df.groupby([jps_df.index.year,jps_df.index.weekday]).mean()

           JPS_TIPO_12B1_WATT  JPS_TIPO_12B2_WATT  JPS_TIPO_11B1_WATT  \
data data
2008 0               9.772676           13.458854            9.884696
     1               9.974155           13.586360           10.034336
     2              10.172917           13.559002           10.088050
     3               9.826522           13.328125            9.906691
     4               9.603946           13.260196            9.734696
     5               7.604988           10.435857            7.694912
     6               6.833894            9.624018            6.905048
2009 0              11.522256           12.569251           11.394451
     1              11.868590           13.036719           11.786579
     2              12.332292           13.503325           12.215785
     3              12.343082           13.633314           12.212873
     4              11.818329           13.182272           11.725741
     5               9.305889           10.209255            9.237941
     6               8.413662            9.323057            8.361478
2010 0              14.126883           14.003906           13.975641
     1              13.834976           13.694772           13.662460
     2              14.056871           13.911538           13.897917
     3              14.167208           13.958854           14.005248
     4              13.864957           13.706388           13.695991
     5              11.109255           10.960857           10.994231
     6              10.151522           10.053025           10.048778
2011 0              14.402264           14.672616           14.223137
     1              14.251983           14.674459           14.124720
     2              14.169391           14.659796           14.128846
     3              14.320593           14.744331           14.177905
     4              13.989062           14.393950           13.855329
     5              11.119340           11.533844           11.020499
     6              10.110557           10.458494           10.017568
2012 0               9.301101           12.797602            9.221875
     1               9.563101           13.230429            9.472396
     2               9.557813           13.172937            9.476482
     3               9.504848           13.260317            9.412981
     4               8.899139           12.763442            8.842408
     5               6.357813           10.175601            6.309475
     6               5.432724            9.304029            5.391293
2013 0              12.282091           12.713662           12.336478
     1              12.292414           12.866116           12.288365
     2              12.159776           12.563281           12.059295
     3              12.115084           12.237460           12.025741
     4              12.034736           12.370853           11.939824
     5               9.335637            9.582973            9.266546
     6               8.573958            8.853546            8.512340

           JPS_TIPO_11B2_WATT  JPS_TIPO_21L1_WATT  JPS_TIPO_21L2_WATT  \
data data
2008 0              13.321094            2.935334            1.272461
     1              13.486380            2.993296            1.341975
     2              13.422877            3.002551            1.370099
     3              13.198498            2.943637            1.336340
     4              13.125240            2.846724            1.247124
     5              10.327784            2.166211            0.733620
     6               9.521534            1.966356            0.579422
2009 0              12.457752            2.989369            1.374248
     1              12.820994            3.121528            1.441728
     2              13.330689            3.252267            1.506956
     3              13.295951            3.239530            1.517589
     4              13.094591            3.054954            1.338327
     5              10.014103            2.318764            0.814584
     6               9.070653            2.106349            0.648695
2010 0              13.870653            3.513030            1.539596
     1              13.557131            3.501379            1.527518
     2              13.739904            3.583861            1.535379
     3              13.846534            3.590359            1.566510
     4              13.579304            3.400493            1.490550
     5              10.851162            2.609811            0.859958
     6               9.959215            2.386468            0.696591
2011 0              14.545413            3.649860            1.560452
     1              14.510657            3.646106            1.536764
     2              14.541927            3.661010            1.546694
     3              14.618890            3.670799            1.543846
     4              14.364704            3.566122            1.442294
     5              11.431977            2.709131            0.861687
     6              10.367788            2.448221            0.679674
2012 0              12.678833            3.618751            1.553387
     1              13.176082            3.751591            1.600418
     2              13.066526            3.754658            1.605969
     3              13.150781            3.770287            1.544986
     4              12.662660            3.537628            1.429253
     5              10.084876            2.671291            0.907634
     6               9.220460            2.432448            0.679236
2013 0              12.573117            3.968702            1.681745
     1              12.748447            3.931284            1.691530
     2              12.451743            3.867127            1.641931
     3              12.308974            3.818672            1.609593
     4              12.341907            3.809310            1.500238
     5               9.494211            2.932722            0.954347
     6               8.769571            2.760531            0.780649

           JPS_TIPO_21L3_WATT  JPS_TIPO_21L4_WATT  JPS_TIPO_21L5_WATT  \
data data
2008 0               2.068578            2.338100            1.684128
     1               2.092454            2.368235            1.715175
     2               2.092854            2.375470            1.735289
     3               2.029541            2.295504            1.695333
     4               2.065622            2.322486            1.626220
     5               1.242620            1.692146            1.024413
     6               0.859204            1.476510            0.797127
2009 0               1.981426            3.309241            1.619789
     1               2.076529            3.433199            1.716158
     2               2.151974            3.558187            1.785007
     3               2.149524            3.552254            1.782207
     4               2.064478            3.481834            1.661093
     5               1.261606            2.688249            0.989310
     6               0.889912            2.324293            0.800368
2010 0               2.318332            3.798748            1.893188
     1               2.278459            3.718780            1.857625
     2               2.334211            3.810714            1.887314
     3               2.350681            3.836121            1.891317
     4               2.259747            3.773559            1.781816
     5               1.404427            2.928132            1.117762
     6               1.003601            2.569320            0.888430
2011 0               2.440967            4.087130            1.930100
     1               2.411722            4.059123            1.918314
     2               2.409463            4.079081            1.899583
     3               2.438002            4.086800            1.913816
     4               2.399403            4.081676            1.854561
     5               1.483609            3.235667            1.172470
     6               1.061359            2.836590            0.925144
2012 0               2.411456            2.652530            1.933904
     1               2.469869            2.706278            2.010131
     2               2.484711            2.697338            2.013490
     3               2.477373            2.749323            2.006621
     4               2.312593            2.664047            1.864674
     5               1.460114            2.003235            1.201109
     6               1.070536            1.715939            0.947652
2013 0               2.619970            3.648693            2.188445
     1               2.631540            3.603401            2.203599
     2               2.582087            3.460454            2.141055
     3               2.565614            3.484868            2.110790
     4               2.562212            3.525554            2.109290
     5               1.601652            2.789842            1.379371
     6               1.202951            2.540422            1.116750

           JPS_TIPO_21L6_WATT  JPS_TIPO_21L7_WATT  JPS_TIPO_21L8_WATT  \
data data
2008 0               4.242065            2.433515            2.122398
     1               4.305065            2.426174            2.133723
     2               4.257682            2.426730            2.106841
     3               4.218689            2.369591            2.113591
     4               4.180270            2.375276            2.125108
     5               3.362109            1.890102            1.872743
     6               3.204479            1.820977            1.739994
2009 0               3.074524            2.399683            1.990081
     1               3.245608            2.460332            2.057560
     2               3.364206            2.546004            2.120484
     3               3.389904            2.556995            2.140031
     4               3.249868            2.477409            2.091195
     5               2.304076            1.977312            1.873636
     6               2.261134            1.887647            1.756405
2010 0               3.008194            2.690005            2.290836
     1               2.987536            2.641303            2.258642
     2               3.056631            2.702767            2.305905
     3               3.058278            2.727284            2.337183
     4               2.918279            2.669323            2.299399
     5               1.983195            2.230086            2.056054
     6               1.921317            2.137316            1.915332
2011 0               3.190935            2.721725            2.376999
     1               3.210721            2.667335            2.373595
     2               3.181596            2.678280            2.401794
     3               3.185033            2.669950            2.408753
     4               3.068467            2.647016            2.388357
     5               2.110373            2.148861            2.092170
     6               1.986491            2.073379            1.912761
2012 0               3.147100            0.925723            2.354771
     1               3.320629            0.919563            2.453656
     2               3.273733            0.897997            2.433181
     3               3.256552            0.888831            2.456735
     4               3.079942            0.840845            2.380613
     5               2.159054            0.566844            2.042125
     6               2.058242            0.550441            1.872393
2013 0               3.688308            1.451557            2.532138
     1               3.788342            1.415935            2.549855
     2               3.710312            1.385634            2.515526
     3               3.632182            1.374727            2.513378
     4               3.552170            1.351188            2.536056
     5               2.403288            1.050310            2.227056
     6               2.326480            1.071128            2.096376

           JPS_TIPO_21L9_WATT
data data
2008 0               2.985274
     1               2.997364
     2               2.965960
     3               2.944684
     4               2.947016
     5               2.949940
     6               2.908538
2009 0               2.928196
     1               2.990373
     2               3.085126
     3               3.097341
     4               3.065055
     5               3.001433
     6               2.963094
2010 0               3.313048
     1               3.261022
     2               3.323569
     3               3.348214
     4               3.345512
     5               3.308956
     6               3.266620
2011 0               3.331747
     1               3.335547
     2               3.336561
     3               3.339326
     4               3.298864
     5               3.292404
     6               3.240829
2012 0               0.465252
     1               0.483037
     2               0.481751
     3               0.491458
     4               0.476108
     5               0.455137
     6               0.437875
2013 0               2.376425
     1               2.356422
     2               2.341844
     3               2.406883
     4               2.441727
     5               2.432379
     6               2.404219

In [14]:
jps_df_2011 = jps_df[jps_df.index.year==2011]
jps_nulos_2011 = jps_nulos[jps_df.index.year==2011]

In [ ]:
def detecta_outliers(serie, metodo = 'desvio'):